apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ym2hlw9vl-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:3166c7222d2694942fc5094d26b6f0654d1adb91@sha256:2a4d55e678456eec9898e82c9593939ccc5313843fb7c5cb222a8a348e83861a
          name: container-image
