apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ym2hlw9vl-dotnet-basic
  janus-idp.io/tekton: ym2hlw9vl-dotnet-basic
  backstage.io/kubernetes-id: ym2hlw9vl-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ym2hlw9vl-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
